### ISSUE TITLE
Error with StackMob v5.0.2

### ISSUE THREAD

**Issue by johncsuti** [Nathat23/StackMob-5#58] opened 2020-02-28 09:50 UTC
ERROR Could not pass event EntityDeathEvent to StackMob v5.0.2
I am not sure what is causing it the only thing dying right now is iron golems. The server seems to report this at odd intervals and it only happens when there is a player logged on.

**Comment by johncsuti** [comment] 2020-02-28 09:53
This server is running Paper version git-Paper-114 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Aurelien30000** [comment] 2020-02-28 18:18
Please provide us the entire stackstrace / error :)

**Comment by johncsuti** [comment] 2020-02-28 18:47
That’s the thing that’s all the console reports nothing else. I can’t pinpoint what’s wrong.

**Comment by johncsuti** [comment] 2020-02-29 00:16
[Fri, 28. Feb 2020 17:06:51 EST INFO] Fetching all due players...
[Fri, 28. Feb 2020 17:06:51 EST INFO] Fetched due players (0 found).
[Fri, 28. Feb 2020 17:06:55 EST ERROR] Could not pass event EntityDeathEvent to StackMob v5.0.2
That's a few lines before then it repeats the first 2 again.

**Comment by Aurelien30000** [comment] 2020-02-29 10:19
> [Fri, 28. Feb 2020 17:06:51 EST INFO] Fetching all due players...
> [Fri, 28. Feb 2020 17:06:51 EST INFO] Fetched due players (0 found).
> [Fri, 28. Feb 2020 17:06:55 EST ERROR] Could not pass event EntityDeathEvent to StackMob v5.0.2
> That's a few lines before then it repeats the first 2 again.

That's a strange logging system, but without details, we can't really help you :/
I think however your issue is similar to #26, we are working on it ^^ I will notificate you when a test build will be available !

**Comment by johncsuti** [comment] 2020-02-29 20:35
I don't think it is. Its not a logging system without details, there just aren't any to begin with.

I do also get this This is related to #26. The error above is not I don't think a new test build would work but I'm willing to try it.
[15:32:36 ERROR]: Could not pass event EntityDeathEvent to StackMob v5.0.2
java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 62.10574722290039. (attribute base value: 20.0)
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:111) ~[patched_1.15.2.jar:git-Paper-114]
        at uk.antiperson.stackmob.entity.death.KillStepDamage.onSpawn(KillStepDamage.java:30) ~[?:?]
        at uk.antiperson.stackmob.listeners.DeathListener.onStackDeath(DeathListener.java:38) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor494.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-114]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-114]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-114]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-114]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:754) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.Entity.burn(Entity.java:1087) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.Entity.move(Entity.java:692) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.EntityLiving.e(EntityLiving.java:2188) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2624) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.EntityInsentient.movementTick(EntityInsentient.java:525) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.EntityMonster.movementTick(EntityMonster.java:23) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.EntityZombie.movementTick(EntityZombie.java:209) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2383) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.EntityZombie.tick(EntityZombie.java:180) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:759) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.World.a(World.java:858) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:497) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-114]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-114]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by johncsuti** [comment] 2020-02-29 20:39
Also just an update that's the full error DiscordSRV wasn't pushing the full error to console chat on discord.

**Comment by Nathat23** [comment] 2020-03-01 10:21
Closing since this looks to be a duplicate of #26

**Closed by Nathat23** 2020-03-01 10:21 UTC
