### ISSUE TITLE
EntityStackEvent missing?

### ISSUE THREAD

**Issue by kangarko** [Nathat23/StackMob-5#61] opened 2020-03-10 06:50 UTC
I updated from 3.3.3 to 5.0.2 and the EntityStackEvent I use in my API connector to your plugin is missing. How to detect and prevent stacking entity that have certain metadata?

**Comment by LogGits** [comment] 2020-03-12 05:24
I believe this relates to #27

**Comment by Nathat23** [comment] 2020-03-22 12:54
Duplicate of #27

**Closed by Nathat23** 2020-03-22 12:54 UTC
Labels: enhancement
