### ISSUE TITLE
1.15.1 Error

### ISSUE THREAD

**Issue by thecenters** [Nathat23/StackMob-5#40] opened 2020-01-31 20:57 UTC
31.01 14:55:54 [Server] ERROR Could not pass event EntityDeathEvent to StackMob v5.0.2
31.01 14:55:54 [Server] INFO java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 42.27833557128906. (attribute base value: 20.0)
31.01 14:55:54 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:111) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at uk.antiperson.stackmob.entity.death.KillStepDamage.onSpawn(KillStepDamage.java:30) ~[?:?]
31.01 14:55:54 [Server] INFO at uk.antiperson.stackmob.listeners.DeathListener.onStackDeath(DeathListener.java:38) ~[?:?]
31.01 14:55:54 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor463.execute(Unknown Source) ~[?:?]
31.01 14:55:54 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:754) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1113) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1694) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2049) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-66]
31.01 14:55:54 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

**Comment by Nathat23** [comment] 2020-02-03 18:25
Duplicate of #26

**Closed by Nathat23** 2020-02-03 18:25 UTC
