### ISSUE TITLE
"Health must be between 0 and 12.0" Console Error

### ISSUE THREAD

**Issue by sebastiantho** [Nathat23/StackMob-5#179] opened 2021-02-01 23:50 UTC
Getting this console error:
https://pastebin.com/gyLW6HdQ

Here's my config:
https://pastebin.com/ZaBx9v6h

**Comment by sebastiantho** [comment] 2021-02-02 15:12
I updated to the newest version. It is no longer an error but instead a warning. Same message tho.

**Comment by Nathat23** [comment] 2021-02-02 17:07
do you know what causes it?

**Comment by Aurelien30000** [comment] 2021-02-08 18:42
Known for a while :/ You can ignore them, but if you have any info about how to reproduce them, tell us 😅

**Comment by Nathat23** [comment] 2021-02-15 08:49
Duplicate of #26

**Closed by Nathat23** 2021-02-15 08:49 UTC
