### ISSUE TITLE
Erorr. Spigot 1.16.5

### ISSUE THREAD

**Issue by KlaydKladowayIgr** [Nathat23/StackMob-5#193] opened 2021-03-01 15:50 UTC
[Server thread/ERROR]: Could not pass event ChunkUnloadEvent to StackMob v5.4.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.Chunk.unloadCallback(Chunk.java:551) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$6(PlayerChunk.java:299) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:98) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.PlayerChunk.a(PlayerChunk.java:309) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.ChunkMapDistance.a(ChunkMapDistance.java:107) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:273) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.access$4(ChunkProviderServer.java:272) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:568) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.runTasks(ChunkProviderServer.java:269) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:951) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.UnsupportedOperationException: Attempted to unregister entity that isn't stacked!
        at uk.antiperson.stackmob.entity.EntityManager.unregisterStackedEntity(EntityManager.java:94) ~[?:?]
        at uk.antiperson.stackmob.entity.EntityManager.unregisterStackedEntities(EntityManager.java:77) ~[?:?]
        at uk.antiperson.stackmob.listeners.ChunkListener.onChunkUnload(ChunkListener.java:23) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:3015-Spigot-73fb609-b7eed25]
        ... 19 more

**Comment by Nathat23** [comment] 2021-03-06 22:39
Duplicate of #180

**Closed by Nathat23** 2021-03-06 22:39 UTC
