### ISSUE TITLE
Lead dupes when stacked mobs are attached to fences.

### ISSUE THREAD

**Issue by helpmeohgod** [Nathat23/StackMob-5#147] opened 2020-10-06 12:10 UTC
I'm sure you're aware of this issue from the past. My question is when are you planning on fixing it?
Also have you considered on making lead unstack one mob out of a stack? Would be really useful to have.

**Comment by Nathat23** [comment] 2020-10-06 21:12
If your referring to https://github.com/Nathat23/StackMob-5/issues/113, then that was fixed. Unless the issue is still occurring?

Allowing leads to unstack one mob out of a stack was a thing in previous stackmob versions, however the feature was never readded since it meant that players could avoid stacking of their mobs.

**Comment by Nathat23** [comment] 2020-12-08 11:40
This is probably fixed by b1492176e545a61ebe3c0945455f88619dcb2ff7

**Closed by Nathat23** 2020-12-08 11:40 UTC
