### ISSUE TITLE
Issue with drowned mobs

### ISSUE THREAD

**Issue by arturek1666** [Nathat23/StackMob-5#176] opened 2021-01-28 10:14 UTC
I had notice that when zombie transforms into drowned while stacked youget drowned with trident and player can easy make farm of it with should be imposible.
![image](https://user-images.githubusercontent.com/1558228/106122860-1b1c0b00-6151-11eb-83f0-db5ab41c623f.png)
Plugin version: 5.4.1

**Comment by Nathat23** [comment] 2021-01-29 15:12
so what your saying is that if a mob has a trident and drowns it keeps the trident?

**Comment by arturek1666** [comment] 2021-01-29 23:21
nope, let me say it again in details:
In minecraft if a zombie transforms to a drowned there is no chance for a drowned to spawn with trident, like it should be impossible, however because of stacking plugin for some reason if there is 200 stacked drowned that where previously zombie, the drowned spawn with trident in hand, with again should be impossible in java editon of minecraft.

**Comment by Nathat23** [comment] 2021-01-30 09:32
So the problem is that naturally spawned drowned (which have a trident) are stacking with the converted drowned?

**Comment by arturek1666** [comment] 2021-01-30 13:25
Well not really, all zombie that where transform to drowned will spawn with trident (when stacked). But yes it can stack with naturally spawned as well.

**Comment by Aurelien30000** [comment] 2021-02-08 22:01
Just make a basic check on spawn or death (spawn-reason drowned) and clear mainhand/offhand if the entity holds a trident or a shell  🤔

**Comment by Nathat23** [comment] 2021-02-08 22:40
Fixed in above.

**Closed by Nathat23** 2021-02-08 22:40 UTC
Labels: bug
