### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Uronic** [Nathat23/StackMob-5#94] opened 2020-05-19 17:49 UTC
I don't know what this actually means in the game since I do not see any problems in the server but this is the error that appears in console

`[21:37:41 ERROR]: Could not pass event EntityDeathEvent to StackMob v5.1.2
java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 59.7421760559082. (attribute base value: 20.0)
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:112) ~[patched_1.15.2.jar:git-Paper-280]
        at uk.antiperson.stackmob.entity.death.KillStepDamage.onSpawn(KillStepDamage.java:40) ~[?:?]
        at uk.antiperson.stackmob.listeners.DeathListener.onStackDeath(DeathListener.java:40) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor26.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-280]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-280]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-280]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-280]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:767) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.Entity.burnFromLava(Entity.java:545) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.Entity.entityBaseTick(Entity.java:481) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.EntityLiving.entityBaseTick(EntityLiving.java:244) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.EntityInsentient.entityBaseTick(EntityInsentient.java:225) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.Entity.tick(Entity.java:435) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2347) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.EntityZombie.tick(EntityZombie.java:180) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:803) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.World.a(World.java:874) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:528) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1316) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1170) ~[patched_1.15.2.jar:git-Paper-280]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:959) ~[patched_1.15.2.jar:git-Paper-280]
        at java.lang.Thread.run(Thread.java:830) [?:?]`

**Comment by TheAwoo** [comment] 2020-05-23 10:50
Hi,
Getting the same error on 5.1.1 - from what i've gathered it seems to be linked to the difficulty settings and other ways of boosting mob health. The error seems to disappear on easy/medium and get spammy on hard.

```[10:38:32 ERROR]: Could not pass event EntityDeathEvent to StackMob v5.1.1
java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 92.09288787841797. (attribute base value: 20.0)
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:112) ~[patched_1.15.2.jar:git-Paper-183]
        at uk.antiperson.stackmob.entity.death.KillStepDamage.onSpawn(KillStepDamage.java:40) ~[?:?]
        at uk.antiperson.stackmob.listeners.DeathListener.onStackDeath(DeathListener.java:40) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor237.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-183]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:759) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.Entity.entityBaseTick(Entity.java:423) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.EntityLiving.entityBaseTick(EntityLiving.java:244) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.EntityInsentient.entityBaseTick(EntityInsentient.java:225) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.Entity.tick(Entity.java:385) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2334) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.EntityZombie.tick(EntityZombie.java:180) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:794) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.World.a(World.java:862) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:516) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1272) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1133) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:941) ~[patched_1.15.2.jar:git-Paper-183]
        at java.lang.Thread.run(Thread.java:834) [?:?]```

**Comment by Nathat23** [comment] 2020-05-23 10:57
Duplicate of #26 

I'm not sure how difficulty would effect it? As far as I'm aware it just increases mob damage to players, not the other way round.

**Closed by Nathat23** 2020-05-23 10:57 UTC
