### ISSUE TITLE
Console Error Stackmob 5.1.2

### ISSUE THREAD

**Issue by 0liverServers** [Nathat23/StackMob-5#89] opened 2020-05-11 04:53 UTC
https://hastebin.com/uxewotiduf.cs

Using latest version of Tuinity.

Plugin list: Plugins (78): AdvancedRegionMarket, AntiDonkeyDupe, AParkour*, Boss, BuycraftX, ChatReaction, Citizens, CitizensCMD, CleanroomGenerator*, CommandRegions*, CoreProtect, CrateReloaded, CustomCrafting, CustomUknownCommand*, DeathMessagesPrime, DeluxeChat, DeluxeMenus, DeluxeTags*, DiscordSRV, Emotes, Essentials, EssentialsSpawn, EVMIPBlock, ezAuctions, EZRanksPro, FeatherBoard*, FogusCore, GPack, GrapplingHook*, GSit, Harbor, HeadDatabase*, HolographicDisplays, InventoryRollback, Jobs, LagAssist, Lands, LimitPillagers, MarriageMaster, mcMMO, MineableSpawners, MMOItems, MMOLib, MobsToEggs, Multiverse-Core, MVdWPlaceholderAPI*, PermissionsEx*, PlaceholderAPI, PlayerParticles, PlayerVaults, PlayerWarps, Playtimes*, PlugMan, PotionManager*, ProtocolLib, PvPToggle, Quests, QuickShop, RandomTeleport, ServerListPlus*, ShopGUIPlus, ShowItem, SimplePets, spark, Spawners, StackMob, StaffPlus, Stocks, TAB, Vault, VillagerOptimiser, VoteParty, Votifier, VotingPlugin, Vouchers, WolfyUtilities, WorldEdit, WorldGuard

**Comment by Nathat23** [comment] 2020-05-11 08:41
Your provided hastebin is empty.

**Comment by 0liverServers** [comment] 2020-05-11 16:25
Alright, seems all the hastebins I made were deleted I'll upload it again when I get back on my server.

**Comment by FeroxDrood** [comment] 2020-05-16 10:48
Getting the same error https://pastebin.com/ktR9jKmW

**Comment by Nathat23** [comment] 2020-05-16 10:49
Duplicate of #26

**Closed by Nathat23** 2020-05-16 10:49 UTC
