### ISSUE TITLE
Killing a mob produces a stack trace

### ISSUE THREAD

**Issue by heyyitstim** [Nathat23/StackMob-5#71] opened 2020-04-06 06:18 UTC
**Describe the bug**
Killing mobs in a stack displays an error in server console.

**To Reproduce**
Kill a mob in a stack.

**Expected behavior**
For there not to be an error every time a stacked mob is killed.
Other than the error it works fine.

**Bukkit/Spigot AND StackMob version:**
Spigot 1.15.2, StackMob 5.1.0

**Additional context**
`06.04 06:11:17 [Server] Server thread/ERROR Could not pass event EntityDeathEvent to StackMob v5.1.0
06.04 06:11:17 [Server] INFO org.bukkit.event.EventException: null
06.04 06:11:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:721) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1328) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1277) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1124) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(SourceFile:69) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1085) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1545) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1879) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
06.04 06:11:17 [Server] INFO Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 20.0(31.0)
06.04 06:11:17 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:109) ~[Spigot-1.15.2.jar:git-Spigot-6de3d4b-a6f8093]
06.04 06:11:17 [Server] INFO at uk.antiperson.stackmob.entity.death.KillStepDamage.onSpawn(KillStepDamage.java:30) ~[?:?]
06.04 06:11:26 [Multicraft] Skipped 7 lines due to rate limit (30/s)`

**Comment by Nathat23** [comment] 2020-04-06 07:59
Duplicate of #26 
There has been a solution made, which can be found in my latest comment in that issue. Please confirm if that fixes your error.

**Closed by Nathat23** 2020-04-06 07:59 UTC
